version: '2'

services:
  mariadb:
    image: linuxserver/mariadb:arm32v7-latest
    ports:
      - '3306:3306'
    volumes:
      - ./data/mariadb:/config
    environemnts:
      - PUID=1000
      - PGID=1000
      - MYSQL_DATABSE=docker
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=docker
    restart: on-failure
    env_file:
      - docker.env
  nginx:
    image: arm32v7/nginx
    ports:
      - '80:80'
    restart: on-failure
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ~/Projects:/code
  php-fpm:
    build: php-fpm
    restart: on-failure
    volumes:
      - ./php-fpm/php.ini:/usr/local/etc/php/conf.d/custom.ini
      - ~/Projects:/code
